Add run_wine_command for better handling of wine
ArmchairDevelopers/Maxima pull request #1
Opened 2023-12-19 11:19 UTC by wannkunstbeikor

This probably sucks ass, since its my first time using rust, but it seems to work

2023-12-19 15:15 UTC, battledash requested changes
Looks good, just a couple notes! Also, please capitalize the comments.

2023-12-19 15:15 UTC, battledash commented on maxima-lib/src/unix/wine.rs
> +
Remove newline

2023-12-19 15:15 UTC, battledash commented on maxima-lib/src/unix/wine.rs
> +    run_wine_command("wine", "reg", Some(vec!["add", "HKLM\\Software\\Origin", "/v", "ClientPath",  "/d", "C:/Windows/System32/conhost.exe", "/f", "/reg:32"]))?;
Are you sure the reg:32 and reg:64 don't need to be swapped here? Afaik in 64-bit mode entries are placed into Wow6432Node, and that needs to happen with the Origin key, not the EA Desktop one. Can you verify with regedit in the wineprefix if the Origin key is placed in Wow6432Node here?

2023-12-19 16:48 UTC, wannkunstbeikor commented on maxima-lib/src/unix/wine.rs
> +    run_wine_command("wine", "reg", Some(vec!["add", "HKLM\\Software\\Origin", "/v", "ClientPath",  "/d", "C:/Windows/System32/conhost.exe", "/f", "/reg:32"]))?;
yeah i checked, it works like this

2023-12-19 16:50 UTC, wannkunstbeikor commented on maxima-lib/src/unix/wine.rs
> +    run_wine_command("wine", "reg", Some(vec!["add", "HKLM\\Software\\Origin", "/v", "ClientPath",  "/d", "C:/Windows/System32/conhost.exe", "/f", "/reg:32"]))?;
> When a 32-bit application queries a value under the HKEY_LOCAL_MACHINE\SOFTWARE\<company>\<product> subkey, the application reads from the HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\<company>\<product> subkey.

2023-12-19 16:50 UTC, wannkunstbeikor commented on maxima-lib/src/unix/wine.rs
> +    run_wine_command("wine", "reg", Some(vec!["add", "HKLM\\Software\\Origin", "/v", "ClientPath",  "/d", "C:/Windows/System32/conhost.exe", "/f", "/reg:32"]))?;
from https://www.itprotoday.com/windows-78/whats-wow6432node-under-hkeylocalmachinesoftware-registry-subkey

2023-12-19 20:13 UTC, battledash commented on maxima-lib/src/unix/wine.rs
> +    run_wine_command("wine", "reg", Some(vec!["add", "HKLM\\Software\\Origin", "/v", "ClientPath",  "/d", "C:/Windows/System32/conhost.exe", "/f", "/reg:32"]))?;
Ah kk

2023-12-19 23:05 UTC, wannkunstbeikor commented on maxima-lib/src/unix/wine.rs
> +
which one, 128?

2023-12-19 23:07 UTC, wannkunstbeikor commented on maxima-lib/src/unix/wine.rs
> +
or should i just do 
`bail!("{}", status.code().unwrap());`

2023-12-19 23:25 UTC, battledash commented on maxima-lib/src/unix/wine.rs
> +
Yeah that works too

2023-12-20 00:17 UTC, battledash approved these changes

2023-12-20 00:18 UTC, merged