UI rework
ArmchairDevelopers/Maxima pull request #9
Opened 2024-01-04 11:23 UTC by headassbtw

Reworks the UI bridge code in a lot of ways:

- Blitzes the games in, no waiting on image/detail loading
- FIXED THE GAME IMAGE SYSTEM (now called `UIImage`, subject to change) I hated it so much and now it actually makes sense to use
- Game images and details now async load when the game is selected, and show a placeholder for a skeleton when they're not loaded
- Games now show the system requirements
- Probably some other cleanup things I forgot, I feel like I'm actually in control of my codebase now
- Fixed the app BG vignette on high-DPI configurations

2024-01-06 03:54 UTC, battledash requested changes

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/util/markdown.rs
> +    while rtn.len() > idx && rtn[idx..].find("<img").is_some() && rtn[idx..].find(">").is_some() {
Add newlines to separate the idx line here

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/util/markdown.rs
> +    // link corrector
Add a newline before the comment here

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/util/markdown.rs
> +    rtn.replace("/", "\\/") // links are caught in the crossfire of this, but clicking them still leads to where they shouold
typo in the comment

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/views/game_view.rs
> +  let game_details: Option<&GameDetails> = match &game.details {
Newline here

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/views/game_view.rs
> +                        stats.label(RichText::new(format!(": {:?} / {:?}",details.achievements_unlocked,details.achievements_total)).color(Color32::BLACK));
These are some very long lines

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/views/game_view.rs
> +              if logo.size.x >= logo.size.y {
This shouldn't be 2 lines

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/main.rs
> +                    });
This should be indented, and the huge line should be split up

2024-01-06 03:54 UTC, battledash commented on maxima-ui/src/translation_manager.rs
> +    pub rec_system_req : String,
There shouldn't be a space before the colons here

2024-01-06 04:01 UTC, battledash requested changes

2024-01-06 04:01 UTC, battledash commented on maxima-ui/src/bridge/login_creds.rs
> +    }
Why's this in a block?

2024-01-06 04:01 UTC, battledash commented on maxima-ui/src/game_info_image_handler.rs
> +          if let Ok(mut file) = File::create(&file_name).await {
Please try to code guard this

2024-01-06 04:01 UTC, battledash commented on maxima-ui/src/game_info_image_handler.rs
> +  let fs_load = ImageLoader::load_from_fs(&file_name.to_str().unwrap());
Newline here

2024-01-06 04:01 UTC, battledash commented on maxima-ui/src/interact_thread.rs
> +                let _ = die_fallback_transmittter
No need to make this a variable

2024-01-06 04:01 UTC, battledash commented on maxima-ui/src/main.rs
>          if let Ok(rcv) = self.backend.rx.try_recv() {
Can this be a separate function?

2024-01-06 06:39 UTC, battledash requested changes

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +                            maxima.service_layer().request(SERVICE_REQUEST_GAMEIMAGES, ServiceGameImagesRequestBuilder::default().should_fetch_context_image(!has_logo).should_fetch_backdrop_images(!h
Make this request multiple lines, one line for each function call

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +                        if !has_hero || !has_logo { //game hasn't been cached yet
What's with the crazy indenting here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +                if let Some(img) = &pack.aspect_2x1_image() {
Are code guards possible here too?

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +                if let Some(img) = &logos.largest_image() {
And here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +    let ctx = ctx.clone();
Newline here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +        let logo = UIImage::load(
Newline here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/game_images.rs
> +        let hero = hero.await;
And here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/get_games.rs
> +    if let Some(games) = owned_games.owned_game_products() {
```rust
let owned_game_products = owned_games.owned_game_products();
if owned_game_products.is_none() {
    return Ok(());
}

for game in owned_game_products.unwrap().items() {
```

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/bridge/get_games.rs
> +        return Err(Error::msg("Not logged in."));
`bail!` here

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/frontend_processor.rs
> +                }
```rust
if !res.success {
    warn!("Login failed.");
    app.in_progress_credential_status = res.description;
    continue;
}

...
```

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/frontend_processor.rs
> +                    if let Ok(resp) = &res.response {
```rust
if res.response.is_err() {
    continue;
}
```

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/frontend_processor.rs
> +                        if game.slug == res.slug {
```rust
if game.slug != res.slug {
   continue;
}
```

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/fs/image_loader.rs
> +            if let Ok(img_decoded) = img.decode() {
You already know what I'm gonna say PepeLaugh

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/ui_image.rs
> +pub async fn write_image_at_url_to_file(url: String, file_name: &PathBuf) -> Result<()>{
`download_image`

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/ui_image.rs
> +
Remove this newline

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/ui_image.rs
> +    let body= result?.bytes().await?;
Add a newline before this and a space after body

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/ui_image.rs
> +
Remove this newline too

2024-01-06 06:39 UTC, battledash commented on maxima-ui/src/ui_image.rs
> +    Ok(())
```rust
    if let Err(err) = io::copy(&mut body.as_slice(), &mut file?).await {
        error!("Failed to copy file! Reason: {:?}", err)
    }

    debug!("Copied file!")
    Ok(())
```

2024-01-06 07:08 UTC, headassbtw commented on maxima-ui/src/bridge/game_images.rs
> +                        if !has_hero || !has_logo { //game hasn't been cached yet
LMAO

2024-01-07 06:33 UTC, battledash approved these changes

2024-01-07 06:44 UTC, merged